// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://wsytmrzgvkvbufpqqxwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzeXRtcnpndmt2YnVmcHFxeHdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ5MDE5OTMsImV4cCI6MjA5MDQ3Nzk5M30.HtuaCGLFiQ7hvpLpaS0RC3YPk5O4Lnft5cmY2XVpgtw";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);